# Generated by Django 3.1.4 on 2021-02-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='First_name',
            field=models.CharField(default='string', max_length=10),
        ),
        migrations.AddField(
            model_name='login',
            name='Last_name',
            field=models.CharField(default='string', max_length=10),
        ),
    ]
