# Generated by Django 3.1.4 on 2021-02-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210227_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Email',
            field=models.EmailField(default='string', max_length=254),
        ),
    ]
