# Generated by Django 3.1.4 on 2021-02-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='login',
            name='First_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='Last_name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
