# Generated by Django 3.1.4 on 2021-03-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210227_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
